name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  web-deploy:

    name: Deploy Angular App
    runs-on: ubuntu-latest

    env:
      SERVER: 141.136.43.17

    steps:
      - name: Get latest code
        uses: actions/checkout@v2.3.2

      - name: Use Node.js 14 LTS
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install NPM Modules
        run: npm ci

      - name: Build Project
        run: npm run build:client-prod

      - name: Ftp upload
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ env.SERVER }}
          username: ${{ secrets.PROD_USER }}
          password: ${{ secrets.PROD_PASSWORD }}
          local-dir: ./dist/apps/jadi-comunnity/
          server-dir: ./
          dangerous-clean-slate: true
